#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: [Your Name] | Reg No: [Your Reg No]
# Course: Open Source Software | Chosen Software: Linux Kernel
# Purpose: Interactively generates a personalised open source philosophy statement

# --- Alias concept demonstrated (alias cannot be used in scripts directly,
#     but we show the concept via a named function, which is the scripting equivalent) ---
print_divider() {
    echo "========================================================"
}

# --- Introduction ---
print_divider
echo "     The Open Source Manifesto Generator"
echo "     Inspired by the Linux Kernel & GNU Philosophy"
print_divider
echo ""
echo "  Answer three questions to generate your personal"
echo "  open source manifesto."
echo ""

# --- Read user input interactively ---
read -p "  1. Name one open-source tool you use every day: " TOOL
read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "  3. Name one thing you would build and share freely: " BUILD

# --- Get current date and username for the output file ---
DATE=$(date '+%d %B %Y')
AUTHOR=$(whoami)

# --- Output filename personalised to the user ---
OUTPUT="manifesto_${AUTHOR}.txt"

# --- Compose the manifesto paragraph using string concatenation ---
echo ""
print_divider
echo "  Generating your manifesto..."
print_divider

# --- Write manifesto to file using > (overwrite) and >> (append) ---
echo "===== My Open Source Manifesto =====" > "$OUTPUT"
echo "Generated by : $AUTHOR" >> "$OUTPUT"
echo "Date         : $DATE" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "I believe in the power of open source, because every day I rely on $TOOL —" >> "$OUTPUT"
echo "a tool built not for profit, but for people. To me, freedom means $FREEDOM." >> "$OUTPUT"
echo "That is the same freedom that Linus Torvalds exercised in 1991 when he" >> "$OUTPUT"
echo "released the Linux Kernel to the world, asking for nothing in return but" >> "$OUTPUT"
echo "collaboration and honesty." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "One day, I intend to build $BUILD and release it freely — because the software" >> "$OUTPUT"
echo "I depend on today was given to me freely by someone I will never meet." >> "$OUTPUT"
echo "Open source is not just a license. It is a promise: that knowledge shared" >> "$OUTPUT"
echo "multiplies, and knowledge hoarded diminishes. I choose to share." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "— $AUTHOR | $DATE" >> "$OUTPUT"
echo "=====================================" >> "$OUTPUT"

# --- Display the saved manifesto ---
echo ""
cat "$OUTPUT"
echo ""
echo "  Manifesto saved to: $OUTPUT"
print_divider
